INSERT INTO CLIENTE (ID, NOME, CPF) VALUES (NULL, 'Fulano da Silva', '11111111111');
INSERT INTO PRODUTO (ID, DESCRICAO, PRECO_UNITARIO) VALUES (NULL, 'Kibe Frito', '8.90');
INSERT INTO PRODUTO (ID, DESCRICAO, PRECO_UNITARIO) VALUES (NULL, 'Cupcake', '9.50');